### ISSUE TITLE
can not gulp

### ISSUE THREAD

**Issue by xieyuheng** [frantic1048/es6-webpack-karma-boilerplate#1]
```
  ~/lang/js/lib/es6-webpack-karma-biolerplate master
gulp --version
[14:44:21] Requiring external module babel-core/register
[14:44:21] CLI version 3.9.0
[14:44:21] Local version 4.0.0-alpha.2

1  ~/lang/js/lib/es6-webpack-karma-biolerplate master
npm install
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6
npm WARN es6-webpack-karma-biolerplate@1.0.2 No repository field.

  ~/lang/js/lib/es6-webpack-karma-biolerplate master
gulp          
[14:44:27] Requiring external module babel-core/register
[14:44:29] Using gulpfile ~/lang/js/lib/es6-webpack-karma-biolerplate/gulpfile.babel.js
/usr/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/lib/node_modules/gulp/bin/gulp.js:129:19
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:139:18)
    at node.js:999:3

1  ~/lang/js/lib/es6-webpack-karma-biolerplate master


```

**Comment by frantic1048** [comment]
It seems your CLI gulp version too low. Try

``` bash
npm install -g gulpjs/gulp.git#4.0
```

install a global Gulp 4.

**Comment by frantic1048** [comment]
This project was fully lightened and tested, take a look in the new one :)

**Comment by xieyuheng** [comment]
```
I am going to use it for sure :)

how about we change the name of the repo a little cuter,
and to use the wiki to explain the tools been used ?
I hope a Chinese wiki firstly :)
```

**Comment by frantic1048** [comment]
Thanks for the response.

"cuter" means more kawaiiness ? 
I'm trying to keep the name direct to topic as possible so that it will be easy to search out, if any suggestion I'll take a consideration on it.

Soon I'll work on the wiki :)
